'use client';
import Link from 'next/link';
import { Search, ArrowRight, Zap, Heart, HeartHandshake, Sparkles } from 'lucide-react';
import { useProfile } from './providers';
import { ModelProgress, useModelStatus } from './model';
import { RecommendationCard, useRecommendations } from './recommendations';
import { ErrorNotice, Skeleton, Empty } from './ui';
export function HomePage() {
  const { profile } = useProfile();
  const model = useModelStatus();
  const recommendations = useRecommendations(6);
  return <><section className="home-hero"><div className="hero-orbit" aria-hidden="true"><span /><span /><Sparkles /></div><div className="home-hero-copy"><p className="eyebrow">UM UNIVERSO DE HISTÓRIAS. O SEU GOSTO.</p><h1>Olá, {profile.name}.<br /><span>O próximo favorito<br />começa com você.</span></h1><p>Filmes, séries e pessoas que ficam com a gente.<br />Descubra o que combina com o seu momento.</p><Link href="/search" className="button"><Search size={18} />Encontrar uma história</Link></div></section><div className="home-actions"><Link href="/quick" className="action-tile"><span className="action-icon"><Zap /></span><div><h2>Avaliação rápida</h2><p>Já assistiu? Um toque e a próxima.</p></div><ArrowRight /></Link><Link href="/genres" className="action-tile"><span className="action-icon"><Heart /></span><div><h2>Seus gostos</h2><p>Conte quais gêneros te conquistam.</p></div><ArrowRight /></Link><Link href="/together" className="action-tile"><span className="action-icon"><HeartHandshake /></span><div><h2>Hoje é para nós</h2><p>Uma boa história para compartilhar.</p></div><ArrowRight /></Link></div><section className="section"><div className="section-heading"><h2>Seu gosto em construção</h2><Link href="/model">Meu modelo<ArrowRight size={15} /></Link></div><div className="panel home-model">{model.isPending ? <Skeleton count={1} /> : model.error ? <ErrorNotice message={model.error.message} retry={() => void model.refetch()} /> : <><ModelProgress status={model.data} /><div><h3>{model.data.trainedAt ? 'Um olhar que aprende com você' : 'Cada avaliação faz diferença'}</h3><p>{model.data.trainedAt ? `${model.data.ratingsUsedInLastTraining} avaliações no último treino · ${model.data.newRatingsSinceLastTraining} novas` : 'Avalie filmes e séries para liberar seu primeiro modelo. Com 8 você já pode experimentar; 25 é a base recomendada.'}</p><Link href="/quick" className="button subtle">Continuar avaliando<ArrowRight size={16} /></Link></div></>}</div></section><section className="section"><div className="section-heading"><div><p className="eyebrow">VALE DESCOBRIR</p><h2>Escolhas para você</h2></div><Link href="/for-you">Ver todas<ArrowRight size={16} /></Link></div>{recommendations.isPending ? <Skeleton count={6} /> : recommendations.error ? <ErrorNotice message={recommendations.error.message} retry={() => void recommendations.refetch()} /> : recommendations.data.length ? <div className="content-grid">{recommendations.data.map(item => <RecommendationCard item={item} key={item.content.id} />)}</div> : <Empty title="O catálogo está esperando novas histórias" message="Busque e importe seus primeiros títulos para começar." />}</section></>;
}
